//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public Nullable<int> CaTrucID { get; set; }
        public Nullable<int> CanBoID { get; set; }
        public string GhiChu { get; set; }
        public int PhanCongID { get; set; }
    
        public virtual CanBo CanBo { get; set; }
        public virtual CaTruc CaTruc { get; set; }
    }
}
